morning-came=<aqua>朝が来た！
night-not-skipped=<aqua>夜はスキップされませんでした！
vote-not-started=<aqua>夜スキップ投票は始まっていません。
its-not-night=<aqua>夜スキップ投票は夜にしかできません。
vote-cancelled=<aqua>投票がキャンセルされました。
to-cancel-vote=<aqua>投票をキャンセルするには、ベッドをクリックするか /sv cancel
vote-to-skip-night=<aqua>夜をスキップするには、一度ベッドに入るか /sv skip
player-voted=<aqua><player> が投票しました！
start-sleeping-vote=<aqua>夜スキップ投票が始まりました。
you-already-voted=<aqua>すでにスキップするに投票しています。
you-already-voted-noskip=<aqua>すでにスキップしないに投票しています。
you-have-not-voted-yet=<aqua>まだ投票していません。
you-do-not-vote-now=<aqua>あなたは現在投票していません。
your-vote-is=<aqua>あなたの投票: <state>.
skip-percentage=<aqua>スキップする: <count>
noskip-percentage=<aqua>スキップしない: <count>
unknown-subcommand=<aqua>未知のサブコマンドです。
vote-tonight-ended=<aqua>今夜の投票は終了しました。
cannot-vote-tonight=<aqua>今夜は投票できません。
reloaded=<aqua>設定ファイルが再読み込みされました。
skip-time-bar-title=<aqua>夜スキップ投票中 /sv skip or /sv noskip (<time_left>/<expire>秒)
skip-time-bar-title-with-interval=<aqua>夜スキップ投票中 /sv skip or /sv noskip (<time_left>/<expire>秒) <interval>日後スキップ不可
next-no-skip-night=<aqua>次のスキップ不可能な夜 : <interval>日後
