[versions]

# common libraries
mcmsgdef = "1.3.0"

# gradle plugins
gradle-plugins = "1.8.5"

# platform api
paper = "26.2.build.119-stable"

[libraries]

# common libraries
mcmsgdef = { module = "dev.siroshun.mcmsgdef:mcmsgdef", version.ref = "mcmsgdef" }

# platform api
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]

bundler = { id = "dev.siroshun.gradle.plugins.bundler", version.ref = "gradle-plugins" }
jcommon = { id = "dev.siroshun.gradle.plugins.jcommon", version.ref = "gradle-plugins" }